# Generated by Django 3.0.3 on 2020-04-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0002_auto_20200418_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigArtist',
        ),
        migrations.DeleteModel(
            name='SmallArtist',
        ),
    ]
